version: "3"

services:
  whisper-mibot:
    build: ./src
    command: sh -c "PYTHONUNBUFFERED=1 python app.py"
    container_name: whisper-mibot
    restart: always
    env_file:
      - .env
    network_mode: host
